services:
  healthtrust:
    build: .
    image: "ghcr.io/leonardoryuta/healthtrust"
    platform: linux/amd64
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - JWT_TOKEN=${JWT_TOKEN}

    restart: unless-stopped
    # volumes:
    # - /run/rofl-appd.sock:/run/rofl-appd.sock